version: '3'

services:

  nats-server:
    image: nats:latest


  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/refined-circuit-429314-q7/nest-course-registry/client-gateway
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/refined-circuit-429314-q7/nest-course-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/refined-circuit-429314-q7/nest-course-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-east1-docker.pkg.dev/refined-circuit-429314-q7/nest-course-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}


#Payments
  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: Dockerfile.prod  
    image: southamerica-east1-docker.pkg.dev/refined-circuit-429314-q7/nest-course-registry/payments-ms
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    environment:
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
